name: catbox
description: View cats that are up for adoption.

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.4.4+3"
  firebase_auth: "0.16.0"
  google_sign_in: "4.4.4"
  cloud_firestore: "0.13.5"
  font_awesome_flutter: "8.8.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf

  assets:
    - assets/cats.json
    - images/profile_header_background.png